### ISSUE TITLE
PDF format?

### ISSUE THREAD

**Issue by Mosen111** [rpsystats/practical-ext-of-intro-stats-in-psy-using-R#3]
Hi, not avilable in pdf format?

**Comment by mkmiecik14** [comment]
Hello, thank you for your interest in our work! Unfortunately, we will not be offering PDF versions of the book. This goes against our philosophy that books should be freely available online and subject to user suggestions via pull requests, etc. If we begin to offer PDFs, we fear there may be a version control problem, especially if additions are made.

If you would like a PDF version, feel free to fork the repository and modify the bookdown code to generate PDFs.
